# Generated by Django 3.2.7 on 2021-09-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_enfermeiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacinas', models.CharField(choices=[('1', 'Pfizer'), ('2', 'Sputnik'), ('3', 'AstraZeneca'), ('4', 'CoronaVac')], max_length=1)),
            ],
        ),
    ]
