# Generated by Django 3.2.7 on 2021-09-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=60)),
                ('numero_endereco', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_prioridade', models.CharField(choices=[('1', 'idoso'), ('2', 'Publico Geral'), ('3', 'Academicos de Saude'), ('4', 'Trabalhadores da linha de frente'), ('5', 'Pessoas com Comorbidade'), ('6', 'Gestantes e Lactantes de 18 a 59')], max_length=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='enfermeiro',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['nome']},
        ),
    ]
