# Generated by Django 3.2.7 on 2021-09-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_auto_20210915_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={},
        ),
        migrations.AddField(
            model_name='paciente',
            name='ja_tomou_segunda_dose',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Prioridade',
        ),
    ]
