# Generated by Django 3.2.7 on 2021-09-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_grupos_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='grupos_Prioridade',
            field=models.CharField(choices=[('1', 'idoso'), ('2', 'Publico Geral'), ('3', 'Academicos de Saude'), ('4', 'Trabalhadores da linha de frente'), ('5', 'Pessoas com Comorbidade'), ('6', 'Gestantes e Lactantes de 18 a 59')], default='', editable=False, max_length=1),
        ),
        migrations.DeleteModel(
            name='Grupos_Prioridade',
        ),
    ]
