# Generated by Django 3.2.7 on 2021-09-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_auto_20210915_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='grupos_Prioridade',
            field=models.CharField(choices=[('1', 'idoso'), ('2', 'Publico Geral'), ('3', 'Academicos de Saude'), ('4', 'Trabalhadores da linha de frente'), ('5', 'Pessoas com Comorbidade'), ('6', 'Gestantes e Lactantes de 18 a 59')], default='', max_length=1),
        ),
    ]
